export const loadingActions = {
  LOADING: 'LOADING',
};

export const allTribesActions = {
  GET_TRIBES: 'GET_TRIBES',
  GET_TRIBES_SUCCESS: 'GET_TRIBES_SUCCESS',
  GET_TRIBES_ERROR: 'GET_TRIBES_ERROR',
  ADD_NEW_TRIBE: 'ADD_NEW_TRIBE',
  ADD_NEW_TRIBE_SUCCESS: 'ADD_NEW_TRIBE_SUCCESS',
  ADD_NEW_TRIBE_ERROR: 'ADD_NEW_TRIBE_ERROR',
};

export const tribeActions = {
  GET_TRIBE_BY_ID: 'GET_TRIBE_BY_ID',
  GET_TRIBE_BY_ID_SUCCESS: 'GET_TRIBE_BY_ID_SUCCESS',
  GET_TRIBE_BY_ID_ERROR: 'GET_TRIBE_BY_ID_ERROR',
  CLEAR_ACTIVE_TRIBE: 'CLEAR_ACTIVE_TRIBE',
};

export const currencyActions = {
  GET_CURRENCY_DATA_BY_TRIBE: 'GET_CURRENCY_DATA_BY_TRIBE',
  GET_CURRENCY_DATA_BY_TRIBE_SUCCESS: 'GET_CURRENCY_DATA_BY_TRIBE_SUCCESS',
  GET_CURRENCY_DATA_BY_TRIBE_ERROR: 'GET_CURRENCY_DATA_BY_TRIBE_ERROR',
  SEND_TRANSACTION: 'SEND_TRANSACTION',
  SEND_TRANSACTION_SUCCESS: 'SEND_TRANSACTION_SUCCESS',
  SEND_TRANSACTION_ERROR: 'SEND_TRANSACTION_ERROR',
};

export const userWalletActions = {
  GET_USER_WALLET_ADDRESS: 'GET_USER_WALLET_ADDRESS',
  GET_USER_WALLET_ADDRESS_SUCCESS: 'GET_USER_WALLET_ADDRESS_SUCCESS',
  GET_USER_WALLET_ADDRESS_ERROR: 'GET_USER_WALLET_ADDRESS_ERROR',
  GET_USER_WALLET_BALANCE: 'GET_USER_WALLET_BALANCE',
  GET_USER_WALLET_BALANCE_SUCCESS: 'GET_USER_WALLET_BALANCE_SUCCESS',
  GET_USER_WALLET_BALANCE_ERROR: 'GET_USER_WALLET_BALANCE_ERROR',
};

export const userSessionActions = {
  GET_USER_SESSION: 'GET_USER_SESSION',
  GET_USER_SESSION_SUCCESS: 'GET_USER_SESSION_SUCCESS',
  GET_USER_SESSION_ERROR: 'GET_USER_SESSION_ERROR',
  PROMPT_AUTHORIZE: 'PROMPT_AUTHORIZE',
  PROMPT_SIGNATURE: 'PROMPT_SIGNATURE',
  GET_USER_SIGNATURE_SUCCESS: 'GET_USER_SIGNATURE_SUCCESS',
};

export const tribePollsActions = {
  GET_TRIBE_POLLS: 'GET_TRIBE_POLLS',
  GET_TRIBE_POLLS_SUCCESS: 'GET_TRIBE_POLLS_SUCCESS',
  GET_TRIBE_POLLS_ERROR: 'GET_TRIBE_POLLS_ERROR',
  ADD_NEW_POLL: 'ADD_NEW_POLL',
  ADD_NEW_POLL_SUCCESS: 'ADD_NEW_POLL_SUCCESS',
  ADD_NEW_POLL_ERROR: 'ADD_NEW_POLL_ERROR',
};

export const tribeProjectsActions = {
  GET_TRIBE_PROJECTS: 'GET_TRIBE_PROJECTS',
  GET_TRIBE_PROJECTS_SUCCESS: 'GET_TRIBE_PROJECTS_SUCCESS',
  GET_TRIBE_PROJECTS_ERROR: 'GET_TRIBE_PROJECTS_ERROR',
  ADD_NEW_PROJECT: 'ADD_NEW_PROJECT',
  ADD_NEW_PROJECT_SUCCESS: 'ADD_NEW_PROJECT_SUCCESS',
  ADD_NEW_PROJECT_ERROR: 'ADD_NEW_PROJECT_ERROR',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_ERROR: 'UPDATE_PROJECT_ERROR',
};

export const tribeTasksActions = {
  GET_TRIBE_TASKS: 'GET_TRIBE_TASKS',
  GET_TRIBE_TASKS_SUCCESS: 'GET_TRIBE_TASKS_SUCCESS',
  GET_TRIBE_TASKS_ERROR: 'GET_TRIBE_TASKS_ERROR',
  ADD_NEW_TASK: 'ADD_NEW_TASK',
  ADD_NEW_TASK_SUCCESS: 'ADD_NEW_TASK_SUCCESS',
  ADD_NEW_TASK_ERROR: 'ADD_NEW_TASK_ERROR',
};
