export const loadingActions = {
  LOADING: 'LOADING',
};

export const allTribesActions = {
  GET_TRIBES: 'GET_TRIBES',
  GET_TRIBES_SUCCESS: 'GET_TRIBES_SUCCESS',
  GET_TRIBES_ERROR: 'GET_TRIBES_ERROR',
};

export const tribeActions = {
  GET_TRIBE_BY_ID: 'GET_TRIBE_BY_ID',
  GET_TRIBE_BY_ID_SUCCESS: 'GET_TRIBE_BY_ID_SUCCESS',
  GET_TRIBE_BY_ID_ERROR: 'GET_TRIBE_BY_ID_ERROR',
  CLEAR_ACTIVE_TRIBE: 'CLEAR_ACTIVE_TRIBE',
};

export const userAddressActions = {
  GET_USER_ADDRESS: 'GET_USER_ADDRESS',
  GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
  GET_USER_ADDRESS_ERROR: 'GET_USER_ADDRESS_ERROR',
};

export const userSessionActions = {
  GET_USER_SESSION: 'GET_USER_SESSION',
  GET_USER_SESSION_SUCCESS: 'GET_USER_SESSION_SUCCESS',
  GET_USER_SESSION_ERROR: 'GET_USER_SESSION_ERROR',
  PROMPT_AUTHORIZE: 'PROMPT_AUTHORIZE',
  PROMPT_SIGNATURE: 'PROMPT_SIGNATURE',
  GET_USER_SIGNATURE_SUCCESS: 'GET_USER_SIGNATURE_SUCCESS',
};

export const tribeVotesActions = {
  GET_TRIBE_VOTES: 'GET_TRIBE_VOTES',
  GET_TRIBE_VOTES_SUCCESS: 'GET_TRIBE_VOTES_SUCCESS',
  GET_TRIBE_VOTES_ERROR: 'GET_TRIBE_VOTES_ERROR',
};
